### ISSUE TITLE
Filme secreto antigos não carregam

### ISSUE THREAD

**Issue by VinicBueno** [csamuelsm/filme-secreto#1]
Olá Samuel, tudo bem?

Conheci seu jogo Filme Secreto mas me deparei com um problema, estava jogando o jogo #380 mas não consegui descobrir o filme, quando fui revelar o filme apareceu a resposta do filme #381. Quando tento acessar os jogos antigos para ver a resposta do jogo #380, não carrega. Isso acontece para todos os jogos anteriores. Agora estou curioso sobre qual foi o filme do jogo #380.

**Comment by csamuelsm** [comment]
Olá, @VinicBueno! Estou fechando a issue pois o problema dos jogos antigos foi corrigido! Obrigado por reportar este bug.
